if [[ `uname -m` == 'arm64' ]]; then
    echo M1
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
eval "$(/opt/homebrew/bin/brew shellenv)"
