version: "3.8"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=
      - PGID=
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - :/config
    restart: unless-stopped