tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
# Library and utilities for processing GIFs
brew "giflib"
# Image manipulation library
brew "jpeg", link: true
# Library for manipulating PNG images
brew "libpng"
# Automatic configure script builder
brew "autoconf"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Manage compile and link flags for libraries
brew "pkg-config"
# Vector graphics library with cross-device output support
brew "cairo"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern replacement for 'ls'
brew "exa"
# Generic library support script
brew "libtool"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Improved top (interactive process viewer)
brew "htop"
# Framework for layout and rendering of i18n text
brew "pango"
# Library to render SVG files using Cairo
brew "librsvg"
# Mac App Store command-line interface
brew "mas"
# Fast, highly customisable system info script
brew "neofetch"
# Python dependency management tool
brew "pipenv"
# Object-relational database system
brew "postgresql@14"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Vi 'workalike' with many additional features
brew "vim"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Internet file retriever
brew "wget"
# Application launcher and productivity software
cask "alfred"
# Multi-track audio editor and recorder
cask "audacity"
# Web browser focusing on privacy
cask "brave-browser"
# Free and open-source web browser
cask "chromium"
# App to build and share containerized applications and microservices
cask "docker"
# Personal blockchain for Ethereum development
cask "ganache"
# Web browser
cask "google-chrome"
# HTTP and GraphQL Client
cask "insomnia"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# GPU-based terminal emulator
cask "kitty"
# App to write, plan, collaborate, and get organized
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Collaboration platform for API development
cask "postman"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Team communication and collaboration software
cask "slack"
# System monitor for the menu bar
cask "stats"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Video communication and virtual meeting platform
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "NordVPN", id: 905953485
mas "Xcode", id: 497799835
