tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern replacement for 'ls'
brew "exa"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Improved top (interactive process viewer)
brew "htop"
# Mac App Store command-line interface
brew "mas"
# Fast, highly customisable system info script
brew "neofetch"
# Python dependency management tool
brew "pipenv"
# Object-relational database system
brew "postgresql@14"
# Python version management
brew "pyenv"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Vi 'workalike' with many additional features
brew "vim"
# Tool for creating isolated virtual python environments
brew "virtualenv"
# Internet file retriever
brew "wget"
# Application launcher and productivity software
cask "alfred"
# Multi-track audio editor and recorder
cask "audacity"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Desktop password and login vault
cask "bitwarden"
# App to build and share containerized applications and microservices
cask "docker"
# Tool to write Fedora images to portable media files
cask "fedora-media-writer"
# Reimagine your terminal
cask "fig"
# Web browser
cask "firefox"
# Personal blockchain for Ethereum development
cask "ganache"
# Web browser
cask "google-chrome"
# Vector graphics editor
cask "inkscape"
# HTTP and GraphQL Client
cask "insomnia"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# JetBrains tools manager
cask "jetbrains-toolbox"
# Note taking and to-do application with synchronization capabilities
cask "joplin"
# Wallet desktop application to maintain multiple cryptocurrencies
cask "ledger-live"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Minimal installer for conda
cask "miniconda"
# VPN client for secure internet access and private browsing
cask "nordvpn"
# App to write, plan, collaborate, and get organized
cask "notion"
# Open-source software for live streaming and screen recording
cask "obs"
# Desktop virtualization software
cask "parallels"
# Administration and development platform for PostgreSQL
cask "pgadmin4"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Team communication and collaboration software
cask "slack"
# Graphical client for Git version control
cask "sourcetree"
# System monitor for the menu bar
cask "stats"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin11"
# File transfer application
cask "transmit"
# Open-source code editor
cask "visual-studio-code"
# Multimedia player
cask "vlc"
# Network protocol analyzer
cask "wireshark"
# Video communication and virtual meeting platform
cask "zoom"
mas "Xcode", id: 497799835
