source $HOME/.aliases
PROMPT='%F{blue}%1~%f %# '

# zsh plugins
source $HOME/.zsh_settings/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zsh_settings/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/swj/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/swj/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/swj/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/swj/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<